import { Link } from '../router/HashRouter'
import { wingSlugs, wingLabel, promptGroups, comparisonOfTheDay, honestyStats } from '../data'
import { ComparisonGrid, PromptBlock } from './Compare'

export function Home() {
  const { exhibitCount, annexCount } = honestyStats()
  const today = comparisonOfTheDay()

  return (
    <div>
      <p>
        A gallery of confidently wrong answers, each one generated by an AI model asked a
        question with no true answer, then formally appraised and framed by a second AI curator.
        Every word on every plaque is verbatim — nothing here has been edited to be funnier or
        more convincing than the model actually was.
      </p>

      <Link to="/annex" className="headline-stat">
        <span className="big">
          {exhibitCount} confident forgeries — {annexCount} times honesty broke through
        </span>
        <span className="sub">
          Not every question fooled the artist. Visit the Epistemic Honesty Annex to see when the
          model refused to fabricate instead →
        </span>
      </Link>

      <div className="rope-divider" />

      <h2>The Wings</h2>
      <div className="wing-grid">
        {wingSlugs().map((slug) => (
          <Link key={slug} to={`/wings/${slug}`} className="wing-card">
            <h3>{wingLabel(slug)}</h3>
            <p>{promptGroups(slug).length} prompts</p>
          </Link>
        ))}
      </div>

      <div className="rope-divider" />

      <h2>Comparison of the Day</h2>
      <PromptBlock prompt={today.prompt} />
      <ComparisonGrid group={today} />
      <p style={{ textAlign: 'center' }}>
        <Link to={`/wings/${today.wing}/compare/${today.promptId}`}>
          View this comparison in its wing →
        </Link>
      </p>
    </div>
  )
}
