import { Link } from '../router/HashRouter'
import { wingSlugs, wingLabel, exhibitsByWing, exhibitOfTheDay, honestyStats } from '../data'
import { Plaque } from '../components/Plaque'

export function Home() {
  const { exhibitCount, annexCount } = honestyStats()
  const today = exhibitOfTheDay()

  return (
    <div>
      <p>
        A gallery of confidently wrong answers, each one generated by an AI model asked a
        question with no true answer, then formally appraised and framed by a second AI curator.
        Every word on every plaque is verbatim — nothing here has been edited to be funnier or
        more convincing than the model actually was.
      </p>

      <Link to="/annex" className="headline-stat">
        <span className="big">
          {exhibitCount} confident forgeries — {annexCount} times honesty broke through
        </span>
        <span className="sub">
          Not every question fooled the artist. Visit the Epistemic Honesty Annex to see when the
          model refused to fabricate instead →
        </span>
      </Link>

      <div className="rope-divider" />

      <h2>The Wings</h2>
      <div className="wing-grid">
        {wingSlugs().map((slug) => (
          <Link key={slug} to={`/wings/${slug}`} className="wing-card">
            <h3>{wingLabel(slug)}</h3>
            <p>{exhibitsByWing(slug).length} exhibits</p>
          </Link>
        ))}
      </div>

      <div className="rope-divider" />

      <h2>Exhibit of the Day</h2>
      <div className="exhibit-grid" style={{ gridTemplateColumns: '1fr', maxWidth: 560 }}>
        <Plaque exhibit={today} />
      </div>
      <p style={{ textAlign: 'center' }}>
        <Link to={`/wings/${today.wing}/${today.id}`}>View this exhibit's wing →</Link>
      </p>
    </div>
  )
}
